# Generated by Django 2.2.6 on 2019-10-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Fresh'), (1, 'Queued'), (
                    2, 'Started'), (3, 'Error'), (4, 'Completed'), (5, 'Partial')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('google', models.TextField()),
                ('duckduckgo', models.TextField()),
                ('wikipedia', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('search', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='engine.SearchHistory')),
            ],
        ),
    ]
