# Generated by Django 2.2.6 on 2019-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(
                1, 'Queued'), (2, 'Started'), (3, 'Error'), (4, 'Completed'), (5, 'Partial')], default=1),
        ),
    ]
